name: Charm Build/Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pack charms
        id: pack
        uses: canonical/craft-actions/charmcraft/pack@main
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.7.0
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          upload-image: "true"
          channel: "latest/edge"
          destructive-mode: "false"
          # built-charm-path: ${{ steps.pack.outputs.charms }}
          built-charm-path: "snmp-daemon_focal-amd64.charm,snmp-daemon_jammy-amd64.charm,snmp-daemon_noble-amd64.charm"
      - name: Archive Charm Under Test
        uses: actions/upload-artifact@v4
        with:
          name: "snmp-daemon"
          path: "*.charm"
          retention-days: 5
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
